# Generated by Django 4.1.5 on 2023-08-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What do you want to call this outfit?', max_length=200)),
                ('description', models.TextField(help_text='Describe this outfit to give your clients a better understanding.')),
                ('category', models.CharField(choices=[('Cultural', 'Cultural'), ('Casual', 'Casual'), ('Sports', 'Sports')], default='Cultural', help_text='Choose a category.', max_length=50)),
                ('image', models.ImageField(help_text='Choose an image that will represent your outfit.', upload_to='images')),
                ('price', models.DecimalField(decimal_places=2, help_text='How much is this outfit going to cost?', max_digits=9)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
